# Lab 2. Arrays in MatLab


## Table of Contents
 * [Creating vectors](#creating_vectors)
 * [Creating matrices](#creating_matrices)
 * [Accessing elements of arrays](#accessing_elements_of_arrays)
 * [Operations involving arrays](#operations_involving_arrays)
 * [More ways of creating arrays](#more_ways_of_creating_arrays)
     * [Arithmetic progressions](#arithmetic_progressions)
     * [Geometric and other progressions](#geometric_and_other_progressions)
     * [Building an array out of arrays](#building_an_array_out_of_arrays)
     * [Size of arrays](#size_of_arrays)
     * [Creating an entire matrix in one statement](#creating_an_entire_matrix_in_one_statement)
     * [Creating matrices using diagonals](#creating_matrices_using_diagonals)
     * [Indices as vectors](#indices_as_vectors)

In [1]:
format short, format compact

In order to explore numerous interesting applications using MatLab, it is essential to handle efficiently a large amount of data store in the form of **vectors** or **matrices**, which are collectively called **arrays**.

<a id='creating_vectors'></a>
## Creating vectors

### Row vectors

A row vector is created by listing its elements within a pair of brackets separated by either spaces or commas. For example,

In [2]:
x = [2 3 -6]

x =
     2     3    -6


or

In [3]:
x = [2, 3, -6]

x =
     2     3    -6


### Column vectors
A column vector is created by listing its elements within a pair of brackets separated by semicolons. For example,

In [4]:
w = [2; 3; -6]

w =
     2
     3
    -6


Alternately, one can _transpose_ a row vector to obtain a column vector.

In [5]:
w = [2, 3, -6].'

w =
     2
     3
    -6


**Note:** The MatLab expression ``x.'`` corresponds to $\mathbf{x}^{\mathrm{T}}$, the  transpose of $\mathbf{x}$, while ``x'`` corresponds to $\mathbf{x}^{\mathrm{H}} = (\mathbf{x}^*)^{\mathrm{T}}$, the  Hermitian or conjugate transpose of $\mathbf{x}$.

<a id='creating_matrices'></a>
## Creating matrices

A matrix is formed by listing all its elements within a pair of brackets with the elements in each row separated by either spaces or commas and the rows separated by semicolons. For example,

In [6]:
A = [1 2 3; 4 5 6; 7 8 9]

A =
     1     2     3
     4     5     6
     7     8     9


<a id='accessing_elements_of_arrays'></a>
## Accessing elements of arrays

* Access the $i$th element of $\mathbf{x}$ by
```
>> x(i)
```
* Access the element in the $i$th row and the $j$th column of $A$ by
```
>> A(i,j)
```
* Assign values to a specific element by
```
>> x(i) = 7
```
or 
```
>> A(i,j) = -sqrt(5)
```
* Indices start at 1 in MatLab, not at 0!

**Question.** Let `A` be a $3 \times 3$ matrix in MatLab. What do you think the value of `A(4)`? Can you guess a rule for `A(i)`?

In [7]:
A = [1 2 3; 4 5 6; 7 8 9]

A =
     1     2     3
     4     5     6
     7     8     9


<a id='operations_involving_arrays'></a>
## Operations involving arrays

Viewing (column) vectors as matrices with only one column, we summarize operations among vectors and matrices soley in terms of matrices when no confusion arises. 

* **Addition/subtraction:** "`+`" and "`-`"
  * matrix $\pm$ matrix
  * scalar $\pm$ matrix
* **Multiplication:** "`*`"
  * matrix by matrix
  * matrix by scalar
* **Inner and outer products:** For a column vector `x`,
  * inner product: `x' * x`
  * outer product: `x * x'`
* **Elementwise operators:** "`.*`", "`./`", "`.^`"
 
  For example, given $\mathtt{v} = (v_1, v_2, \ldots, v_n)$ 
  and $\mathtt{w} = (w_1, w_2, \ldots, w_n)$, 
  $$\mathtt{v .* w} = (v_1 w_1, v_2 w_2, \ldots, v_n w_n).$$
  
* **Square matrix to a positive integral power:** "`^`"

  For $\mathtt{A} \in \mathbb{R}^{m \times m}$, 
  ```
  >> A^5
  ```
  and
  ```
  >> A*A*A*A*A
  ```
  yield the same result. 
  
* **Inversion of a square matrix:** "`inv`"

  For $\mathtt{A} \in \mathbb{R}^{m \times m}$, 
  ```
  >> inv(A)
  ```
  and
  ```
  >> A^(-1)
  ```
  produce the same result. 

<a id='more_ways_of_creating_arrays'></a>
## More ways of creating arrays

<a id='arithmetic_progressions'></a>
### Arithmetic progressions

In MatLab, we can create a row vector of an arithmetic progression easily.

**Colon (`:`) operator**:
* `a:d:b` creates a progression from `a` to `b` with increment `d`. 
* When `b-a` is not an integer multiple of `d`, the progression stops at `a + fix((b-a)/d)`. 
* When `d = 1`, one may simply use `a:b`.

In [8]:
0:2:10

ans =
     0     2     4     6     8    10


In [9]:
0:2:11

ans =
     0     2     4     6     8    10


In [10]:
0:10

ans =
     0     1     2     3     4     5     6     7     8     9    10


In [11]:
0:1:10

ans =
     0     1     2     3     4     5     6     7     8     9    10


**Explore.**  See what happens when $\mathtt{b} < \mathtt{a}$? Try different $\mathtt{d}$'s.

**`linspace` function:**
* `linspace(a, b, n)` creates the arithmetic progression of $n$ terms starting at $a$ and ending at $b$.
* `linspace` is more suitable when the number of elements in a progression is known. The colon operator is more appropriate when the difference between successive terms is known.

In [12]:
linspace(0, 10, 11)

ans =
     0     1     2     3     4     5     6     7     8     9    10


In [13]:
linspace(0, 10, 10)

ans =
  Columns 1 through 7
         0    1.1111    2.2222    3.3333    4.4444    5.5556    6.6667
  Columns 8 through 10
    7.7778    8.8889   10.0000


**Example.** Create the *periodic* arithmetic progression 
$$(1,2,3,4,0,1,2,3,4,0,1,2,3,4,0)$$
using the colon operator and `mod` function. 

In [14]:
% Answer
mod((1:15), 5)

ans =
  Columns 1 through 13
     1     2     3     4     0     1     2     3     4     0     1     2     3
  Columns 14 through 15
     4     0


**Exercise.** Create the following row vectors using ONE MatLab statement.
1. $\mathbf{v} = (1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,)$
2. $\mathbf{w} = (1,2,3,4,1,2,3,4,1,2,3,4)$

<a id='geometric_and_other_progressions'></a>
### Geometric and other progressions

Elementwise operations such as "`.*`", "`./`", and "`.^`" are useful in generating progression other than arithmetic ones. 

**Example.** Create 

* $\mathbf{v} = (1, 2, 4, 8,\ldots, 1024)$ 
* $\mathbf{w} = (1, 4, 9, 16, \ldots, 100)$

using ONE MATLAB statement.

In [15]:
v = 2 .^ [0:10]

v =
  Columns 1 through 6
           1           2           4           8          16          32
  Columns 7 through 11
          64         128         256         512        1024


In [16]:
w = [1:10] .^ 2

w =
     1     4     9    16    25    36    49    64    81   100


**Example.** Create 

* $\mathbf{v} = (\sin 0^{\circ}, \sin 30^{\circ}, \sin 60^{\circ}, \ldots, \sin 180^{\circ})$ 
* $\mathbf{w} = (e^1, e^4, e^9, \ldots, e^{64})$

using ONE MATLAB statement.

In [17]:
v = sind(0:30:180)

v =
         0    0.5000    0.8660    1.0000    0.8660    0.5000         0


In [18]:
format short e
w = exp([1:8].^2)

w =
  Columns 1 through 6
   2.7183e+00   5.4598e+01   8.1031e+03   8.8861e+06   7.2005e+10   4.3112e+15
  Columns 7 through 8
   1.9073e+21   6.2351e+27


<a id='building_an_array_out_of_arrays'></a>
### Building an array out of arrays

`reshape(A, m, n)` reshapes an array $A$ into an $m \times n$ matrix whose elements are taken *columnwise* from $A$.

In [19]:
A = reshape(1:20, 4, 5)

A =
     1     5     9    13    17
     2     6    10    14    18
     3     7    11    15    19
     4     8    12    16    20


`repmat(A, m, n)` replicates the array $A$, $m$ times vertically and $n$ times horizontally.

In [20]:
B = repmat([1 2; 3 4], 2, 2)

B =
     1     2     1     2
     3     4     3     4
     1     2     1     2
     3     4     3     4


If $A$ and $B$ have comparable sizes, we can concatenate them:

* vertically: `[A; B]`
* horizontally: `[A B]`

<a id='size_of_arrays'></a>
### Size of arrays

Let $\mathtt{v} \in \mathbb{R}^m$ and $A \in \mathbb{R}^{m \times n}$. Then

* `length(v)` gives the number of elements of $\mathtt{v}$, which is $m$.
* `size(A, 1)` gives the number of rows of $A$, which is $m$.
* `size(A, 2)` gives the number of columns of $A$, which is $n$.
* `size(A)` outputs a two-vector $(m,n)$.
* `numel(A)` returns the total number of elements in $A$, which is $m \times n$.


**Explore.** What are the sizes of `[ ]`, `[1:0]`, and `[1:0].'`? what are their `numel` values?

<a id='creating_an_entire_matrix_in_one_statement'></a>
### Creating an entire matrix in one statement

We can create matrices consisting of all zeros or all ones easily in MATLAB.

In [21]:
zeros(3)

ans =
     0     0     0
     0     0     0
     0     0     0


In [22]:
zeros(3, 4)

ans =
     0     0     0     0
     0     0     0     0
     0     0     0     0


In [23]:
ones(5, 4)

ans =
     1     1     1     1
     1     1     1     1
     1     1     1     1
     1     1     1     1
     1     1     1     1


Identity matrices are easy to construct.

In [24]:
eye(4)

ans =
     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1


**Note.** `zeros([m,n])` yields the same result as `zeros(m,n)`. The same applies to `ones`. So we can do something like this.

In [25]:
A = reshape([1:30], 5, 6)
B = 3*ones(size(A))

A =
     1     6    11    16    21    26
     2     7    12    17    22    27
     3     8    13    18    23    28
     4     9    14    19    24    29
     5    10    15    20    25    30
B =
     3     3     3     3     3     3
     3     3     3     3     3     3
     3     3     3     3     3     3
     3     3     3     3     3     3
     3     3     3     3     3     3


<a id='creating_matrices_using_diagonals'></a>
### Creating matrices using diagonals

We can create a matrix by specifying the diagonal elements. Conversely, the diagonal entries of a certain matrix can be extracted as a vector. 

In [26]:
v = linspace(0, 1, 6)
D = diag(v)

v =
            0   2.0000e-01   4.0000e-01   6.0000e-01   8.0000e-01   1.0000e+00
D =
            0            0            0            0            0            0
            0   2.0000e-01            0            0            0            0
            0            0   4.0000e-01            0            0            0
            0            0            0   6.0000e-01            0            0
            0            0            0            0   8.0000e-01            0
            0            0            0            0            0   1.0000e+00


In [27]:
diag(A)

ans =
     1
     7
    13
    19
    25


In [28]:
diag(A, 1)

ans =
     6
    12
    18
    24
    30


In [29]:
diag(A, -1)

ans =
     2
     8
    14
    20


We can also extract upper or lower triangular entries (above and including $k$th diagonal) of a given matrix.

In [30]:
triu(A)

ans =
     1     6    11    16    21    26
     0     7    12    17    22    27
     0     0    13    18    23    28
     0     0     0    19    24    29
     0     0     0     0    25    30


In [31]:
triu(A, 1)

ans =
     0     6    11    16    21    26
     0     0    12    17    22    27
     0     0     0    18    23    28
     0     0     0     0    24    29
     0     0     0     0     0    30


In [32]:
tril(A,2)

ans =
     1     6    11     0     0     0
     2     7    12    17     0     0
     3     8    13    18    23     0
     4     9    14    19    24    29
     5    10    15    20    25    30


<a id='indices_as_vectors'></a>
### Indices as vectors

We can access multiple elements of an array using vectors. Let $\mathbf{v}$ be a vector and $A$ be a matrix.

* `v(i:j)` returns $i$th through $j$th entries.
* `A(i:j, k:l)` returns the intersection of rows from $i$ to $j$ and columns from $k$ to $l$.
* `v(end)` outputs the last element of $\mathbf{v}$.
* One may assign values to the elements specified by indicial vectors.
* `A(:)` turns $A$ into a column vector. 

In [33]:
v(2:4)

ans =
   2.0000e-01   4.0000e-01   6.0000e-01


In [34]:
A(1:3, 3:end)

ans =
    11    16    21    26
    12    17    22    27
    13    18    23    28


In [35]:
A(:)

ans =
     1
     2
     3
     4
     5
     6
     7
     8
     9
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    20
    21
    22
    23
    24
    25
    26
    27
    28
    29
    30


In [36]:
v

v =
            0   2.0000e-01   4.0000e-01   6.0000e-01   8.0000e-01   1.0000e+00


In [37]:
v(1) = 7
v(2:end) = 0

v =
   7.0000e+00   2.0000e-01   4.0000e-01   6.0000e-01   8.0000e-01   1.0000e+00
v =
     7     0     0     0     0     0
