# Lab 2. Arrays in MatLab

From Au17: see ``lec04.pdf``, ``lec05.pdf``, ``lec06.pdf``, and ``lec07.pdf``

In order to explore numerous interesting applications using MatLab, it is essential to handle efficiently a large amount of data store in the form of **vectors** or **matrices**, which are collectively called **arrays**.

## Creating vectors

### Row vectors

A row vector is created by listing its elements within a pair of brackets separated by either spaces or commas. For example,

In [9]:
x = [2 3 -6]

x =
     2     3    -6


or

In [10]:
x = [2, 3, -6]

x =
     2     3    -6


### Colum vectors
A column vector is created by listing its elements within a pair of brackets separated by semicolons. For example,

In [11]:
w = [2; 3; -6]

w =
     2
     3
    -6


Alternately, one can _transpose_ a row vector to obtain a column vector.

In [12]:
w = [2, 3, -6].'

w =
     2
     3
    -6


**Note:** The MatLab expression ``x.'`` corresponds to $\mathbf{x}^{\mathrm{T}}$, the  transpose of $\mathbf{x}$, while ``x'`` corresponds to $\mathbf{x}^{\mathrm{H}} = (\mathbf{x}^*)^{\mathrm{T}}$, the  Hermitian or conjugate transpose of $\mathbf{x}$.

## Creating matrices

A matrix is formed by listing all its elements within a pair of brackets with the elements in each row separated by either spaces or commas and the rows separated by semicolons. For example,

In [13]:
A = [1 2 3; 4 5 6; 7 8 9]

A =
     1     2     3
     4     5     6
     7     8     9


## Accessing elements of arrays

* Access the $i$th element of $\mathbf{x}$ by
```
>> x(i)
```
* Access the element in the $i$th row and the $j$th column of $A$ by
```
>> A(i,j)
```
* Assign values to a specific element by
```
>> x(i) = 7
```
or 
```
>> A(i,j) = -sqrt(5)
```
* Indices start at 1 in MatLab, not at 0!

**Question.** Let `A` be a $3 \times 3$ matrix in MatLab. What do you think the value of `A(4)`? Can you guess a rule for syntax `A(i)`?

## Operations involving arrays

## More ways of creating arrays

### Example: arithmetic progressions

### Example: geometric and other progressions

### Building an array out of arrays

### Creating an entire matrix in one statement

### Creating matrices using diagonals

### Indices as vectors

## Size of arrays

## Random vectors and matrices

## Accessing elements of arrays (continued)

## Vector and matrix norms

## Tables using matrices

## Data manipulation