# Lab 2. Arrays in MatLab

From Au17: see ``lec04.pdf``, ``lec05.pdf``, ``lec06.pdf``, and ``lec07.pdf``

In [1]:
format short, format compact

In order to explore numerous interesting applications using MatLab, it is essential to handle efficiently a large amount of data store in the form of **vectors** or **matrices**, which are collectively called **arrays**.

## Creating vectors

### Row vectors

A row vector is created by listing its elements within a pair of brackets separated by either spaces or commas. For example,

In [2]:
x = [2 3 -6]

x =
     2     3    -6


or

In [3]:
x = [2, 3, -6]

x =
     2     3    -6


### Colum vectors
A column vector is created by listing its elements within a pair of brackets separated by semicolons. For example,

In [4]:
w = [2; 3; -6]

w =
     2
     3
    -6


Alternately, one can _transpose_ a row vector to obtain a column vector.

In [5]:
w = [2, 3, -6].'

w =
     2
     3
    -6


**Note:** The MatLab expression ``x.'`` corresponds to $\mathbf{x}^{\mathrm{T}}$, the  transpose of $\mathbf{x}$, while ``x'`` corresponds to $\mathbf{x}^{\mathrm{H}} = (\mathbf{x}^*)^{\mathrm{T}}$, the  Hermitian or conjugate transpose of $\mathbf{x}$.

## Creating matrices

A matrix is formed by listing all its elements within a pair of brackets with the elements in each row separated by either spaces or commas and the rows separated by semicolons. For example,

In [6]:
A = [1 2 3; 4 5 6; 7 8 9]

A =
     1     2     3
     4     5     6
     7     8     9


## Accessing elements of arrays

* Access the $i$th element of $\mathbf{x}$ by
```
>> x(i)
```
* Access the element in the $i$th row and the $j$th column of $A$ by
```
>> A(i,j)
```
* Assign values to a specific element by
```
>> x(i) = 7
```
or 
```
>> A(i,j) = -sqrt(5)
```
* Indices start at 1 in MatLab, not at 0!

**Question.** Let `A` be a $3 \times 3$ matrix in MatLab. What do you think the value of `A(4)`? Can you guess a rule for syntax `A(i)`?

## Operations involving arrays

Viewing (column) vectors as matrices with only one column, we summarize operations among vectors and matrices soley in terms of matrices when no confusion arises. 

* **Addition/subtraction:** "`+`" and "`-`"
  * matrix $\pm$ matrix
  * scalar $\pm$ matrix
* **Multiplication:** "`*`"
  * matrix by matrix
  * matrix by scalar
* **Inner and outer products:** For a column vector `x`,
  * inner product: `x' * x`
  * outer product: `x * x'`
* **Elementwise operators:** "`.*`", "`./`", "`.^`"
 
  For example, given $\mathtt{v} = (v_1, v_2, \ldots, v_n)$ 
  and $\mathtt{w} = (w_1, w_2, \ldots, w_n)$, 
  $$\mathtt{v .* w} = (v_1 w_1, v_2 w_2, \ldots, v_n w_n).$$
  
* **Square matrix to a positive integral power:** "`^`"

  For $\mathtt{A} \in \mathbb{R}^{m \times m}$, 
  ```
  >> A^5
  ```
  and
  ```
  >> A*A*A*A*A
  ```
  yield the same result. 
  
* **Inversion of a square matrix:** "`inv`"

  For $\mathtt{A} \in \mathbb{R}^{m \times m}$, 
  ```
  >> inv(A)
  ```
  and
  ```
  >> A^(-1)
  ```
  produce the same result. 

## More ways of creating arrays

### Arithmetic progressions

In MatLab, we can create a row vector of an arithmetic progression easily.

**Colon (`:`) operator**:
* `a:d:b` creates a progression from `a` to `b` with increment `d`. 
* When `b-a` is not an integer multiple of `d`, the progression stops at `a + fix((b-a)/d)`. 
* When `d = 1`, one may simply use `a:b`.

In [7]:
0:2:10 

ans =
     0     2     4     6     8    10


In [8]:
0:2:11

ans =
     0     2     4     6     8    10


In [9]:
0:10

ans =
     0     1     2     3     4     5     6     7     8     9    10


**Explore.**  See what happens when $\mathtt{b} < \mathtt{a}$? Try different `d`'s.

**`linspace` function:**
* `linspace(a, b, n)` creates the arithmetic progression of `n` terms starting at `a` and ending at `b`.
* `linspace` is more suitable when the number of elements in a progression is known. The colon operator is more appropriate when the difference between successive terms is known.

In [10]:
linspace(0, 10, 11)

ans =
     0     1     2     3     4     5     6     7     8     9    10


**Example.** Create the *periodic* arithmetic progression 
$$(1,2,3,4,0,1,2,3,4,0,1,2,3,4,0)$$
using the colon operator and `mod` function. 

In [11]:
% Answer
mod((1:15), 5)

ans =
  Columns 1 through 13
     1     2     3     4     0     1     2     3     4     0     1     2     3
  Columns 14 through 15
     4     0


**Exercise.** Create the following row vectors using ONE MatLab statement.
1. $\mathbf{v} = (1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,)$
2. $\mathbf{w} = (1,2,3,4,1,2,3,4,1,2,3,4)$

### Geometric and other progressions

Elementwise operations such as "`.*`", "`./`", and "`.^`" are useful in generating progression other than arithmetic ones. 

In [12]:
2 .^ [0:10]

ans =
  Columns 1 through 6
           1           2           4           8          16          32
  Columns 7 through 11
          64         128         256         512        1024


In [13]:
[1:10] .^ 2

ans =
     1     4     9    16    25    36    49    64    81   100


In [14]:
sind(0:30:180)

ans =
         0    0.5000    0.8660    1.0000    0.8660    0.5000         0


### Building an array out of arrays

### Creating an entire matrix in one statement

### Creating matrices using diagonals

### Indices as vectors

## Size of arrays

## Random vectors and matrices

## Accessing elements of arrays (continued)

## Vector and matrix norms

## Tables using matrices

## Data manipulation